name: Deploy para o NuGet

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependências
        run: dotnet restore Formula.csproj

      - name: Build do Projeto
        run: dotnet build Formula.csproj --configuration Release --no-restore

      - name: Criar Pacote NuGet
        run: dotnet pack Formula.csproj --configuration Release --no-build -o dist

      - name: Publicar no NuGet
        run: dotnet nuget push dist/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Pack Template
        run: dotnet pack content/NAME.csproj -o dist

      - name: Publish Template
        run: dotnet nuget push dist/NAME.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json